import type { MappingConfig } from './types'

/**
 * Mapping presets: independent from physics presets. Any mapping can be
 * combined with any model; sources that a model does not produce fall back
 * to neutral values (value=0, R=0, …), which is intentional: "Chaos + Spiral
 * Melody" is a different reading of the same simulation.
 */
export const MAPPING_PRESETS: MappingConfig[] = [
  {
    id: 'spiral-melody',
    name: 'Spiral Melody',
    description: 'angle → degree · radius → octave · energy → velocity · ω → brightness · gate/phase → trigger',
    pitchSource: 'angle',
    registerSource: 'radius',
    registerSpan: 2,
    velocitySource: 'energy',
    velocityCurve: 'linear',
    timbreSource: 'acceleration',
    widthSource: 'radius',
    triggerOn: ['gateCrossing', 'phaseCrossing', 'thresholdCrossing', 'periapsis', 'extrema'],
    accentOn: [],
    pitchRangeFromSync: false,
    durationBeats: 0.6,
  },
  {
    id: 'gravity-bass',
    name: 'Gravity Bass',
    description: 'identity → degree · radius → register downward · energy → velocity · centre distance → filter · gate → trigger',
    pitchSource: 'gate',
    registerSource: 'radius',
    registerSpan: 2,
    velocitySource: 'energy',
    velocityCurve: 'invExp',
    timbreSource: 'radiusInverse',
    widthSource: 'constant',
    triggerOn: ['gateCrossing', 'phaseCrossing', 'thresholdCrossing', 'periapsis', 'apoapsis', 'extrema'],
    accentOn: ['centerEntry', 'periapsis'],
    pitchRangeFromSync: false,
    durationBeats: 0.8,
  },
  {
    id: 'spectral-orbit',
    name: 'Spectral Orbit',
    description: 'angle → pitch · speed → octave · periapsis → accent · radius → COLOR',
    pitchSource: 'angle',
    registerSource: 'speed',
    registerSpan: 2,
    velocitySource: 'angularVelocity',
    velocityCurve: 'scurve',
    timbreSource: 'radius',
    widthSource: 'radius',
    triggerOn: ['gateCrossing', 'periapsis', 'apoapsis', 'quadrant', 'phaseCrossing', 'thresholdCrossing'],
    accentOn: ['periapsis'],
    pitchRangeFromSync: false,
    durationBeats: 0.5,
  },
  {
    id: 'swarm-pulse',
    name: 'Swarm Pulse',
    description: 'phase wrap → trigger · oscillator identity → degree · sync R → pitch range & brightness · phase velocity → velocity',
    pitchSource: 'identity',
    registerSource: 'sync',
    registerSpan: 1,
    velocitySource: 'phaseVelocity',
    velocityCurve: 'linear',
    timbreSource: 'sync',
    widthSource: 'syncInverse',
    triggerOn: ['phaseCrossing', 'gateCrossing', 'thresholdCrossing', 'periapsis', 'extrema'],
    accentOn: ['sync'],
    pitchRangeFromSync: true,
    durationBeats: 0.4,
  },
  {
    id: 'chaotic-melody',
    name: 'Chaotic Melody',
    description: 'x → degree · Δx → register · extrema → trigger · |x−0.5| → velocity',
    pitchSource: 'value',
    registerSource: 'valueDelta',
    registerSpan: 2,
    velocitySource: 'distanceFromHalf',
    velocityCurve: 'invExp',
    timbreSource: 'slope',
    widthSource: 'constant',
    triggerOn: ['extrema', 'gateCrossing', 'phaseCrossing', 'periapsis'],
    accentOn: ['thresholdCrossing'],
    pitchRangeFromSync: false,
    durationBeats: 0.5,
  },
  {
    id: 'accelerating-spiral',
    name: 'Accelerating Spiral',
    description: 'identity/gate → pitch · energy → velocity · ω → brightness. Register fixed: only rhythm accelerates.',
    pitchSource: 'gate',
    registerSource: 'none',
    registerSpan: 0,
    velocitySource: 'energy',
    velocityCurve: 'linear',
    timbreSource: 'acceleration',
    widthSource: 'radius',
    triggerOn: ['gateCrossing', 'phaseCrossing', 'thresholdCrossing', 'periapsis', 'extrema'],
    accentOn: [],
    pitchRangeFromSync: false,
    durationBeats: 0.6,
  },
  {
    id: 'falling-into-center',
    name: 'Falling Into Center',
    description: 'gate → pitch · inner = lower register · energy → velocity · centre entry accent',
    pitchSource: 'gate',
    registerSource: 'radius',
    registerSpan: 3,
    velocitySource: 'energy',
    velocityCurve: 'exp',
    timbreSource: 'energy',
    widthSource: 'constant',
    triggerOn: ['gateCrossing', 'centerEntry', 'phaseCrossing', 'thresholdCrossing', 'periapsis', 'extrema'],
    accentOn: ['centerEntry'],
    pitchRangeFromSync: false,
    durationBeats: 1,
  },
  {
    id: 'register-collapse',
    name: 'Register Collapse',
    description: 'angle → degree · inner = higher register (collapses upward) · speed → velocity',
    pitchSource: 'angle',
    registerSource: 'radiusInverse',
    registerSpan: 3,
    velocitySource: 'angularVelocity',
    velocityCurve: 'scurve',
    timbreSource: 'radiusInverse',
    widthSource: 'radius',
    triggerOn: ['gateCrossing', 'phaseCrossing', 'thresholdCrossing', 'periapsis', 'extrema'],
    accentOn: [],
    pitchRangeFromSync: false,
    durationBeats: 0.4,
  },
  {
    id: 'bright-core',
    name: 'Bright Core',
    description: 'gate → pitch · register fixed · brightness opens toward the centre · acceleration → velocity',
    pitchSource: 'gate',
    registerSource: 'none',
    registerSpan: 0,
    velocitySource: 'energy',
    velocityCurve: 'linear',
    timbreSource: 'radiusInverse',
    widthSource: 'radius',
    triggerOn: ['gateCrossing', 'phaseCrossing', 'thresholdCrossing', 'periapsis', 'extrema'],
    accentOn: ['centerEntry'],
    pitchRangeFromSync: false,
    durationBeats: 0.7,
  },
]

export function getMapping(id: string): MappingConfig {
  return MAPPING_PRESETS.find((m) => m.id === id) ?? MAPPING_PRESETS[0]
}
